USE [master]
GO

/****** Object:  Database [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF]    Script Date: 5/4/2018 12:07:58 AM ******/
CREATE DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InterimDB', FILENAME = N'E:\C#\SqlDatabase\SqlDatabase\InterimDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InterimDB_log', FILENAME = N'E:\C#\SqlDatabase\SqlDatabase\InterimDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET ARITHABORT OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET  ENABLE_BROKER 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET  MULTI_USER 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET QUERY_STORE = OFF
GO

USE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [E:\C#\SQLDATABASE\SQLDATABASE\INTERIMDB.MDF] SET  READ_WRITE 
GO


